auctionsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls',namespace='pages')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import ProductCreateView,ProductListView,ProductDetailView,ProductUpdateView,UserProductListView,BidUpdateView
app_name = 'pages'
urlpatterns = [
    path('',ProductListView.as_view(),name='product_list'),
    path('<int:id>/<slug:slug>/',ProductDetailView.as_view(),name='product_detail'),
    path('product/add/',ProductCreateView.as_view(),name='product_add'),
    path('product/edit/<int:id>/<slug:slug>/',ProductUpdateView.as_view(),name='product_edit'),
    path('product/myposts',UserProductListView.as_view(),name='myposts'),
    path('bid/edit/<int:pk>',BidUpdateView.as_view(),name='bid_edit'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):

    def __str__(self):
        return self.email

pages/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
# For Slugify
from django.utils.text import slugify
import string
import random

# To generate differnt slug
def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(6))


class Products(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.CharField(max_length=500)
    minimum_bid_price = models.DecimalField(max_digits=10, decimal_places=2)
    date_posted = models.DateTimeField(auto_now_add=True, blank=True)
    end_time = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    class Meta:
        ordering = ('date_posted',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return str(self.title)

    def save(self, *args, **kwargs):
        if not self.slug:
            # can be added duplicate product with same name
            self.slug = slugify(rand_slug() + "-" + self.title)
        super(Products, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pages:product_detail', args=[self.id, self.slug])


class Bid(models.Model):
    bid_item =models.ForeignKey(Products,on_delete=models.CASCADE,related_name='bid_item')
    bid_price = models.DecimalField(max_digits=10, decimal_places=2)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True, blank=True)

    class Meta:
        ordering =('date_posted',)

    def __str__(self):
        return str(self.created_by)
    
    def get_absolute_url(self):
        return reverse('pages:product_detail', args=[self.bid_item.id, self.bid_item.slug])
   

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

pages/forms.py
from django.forms import ModelForm
from .models import Bid

class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields =['bid_price']
    

accounts/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Products, Bid
from django.urls import reverse_lazy, reverse
from .forms import BidForm
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)


class ProductListView(ListView):
    model = Products
    template_name = 'product/list.html'
    context_object_name = 'products'
    paginate_by = 5
    queryset = Products.objects.all()


class ProductDetailView(FormMixin, DetailView):
    model = Products
    form_class = BidForm
    template_name = 'product/detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bidder'] = Bid.objects.all().order_by('-bid_price').first()
        context['bid'] = Bid.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.bid_item_id = self.object.pk
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('pages:product_detail', kwargs={'id': self.object.pk, 'slug': self.object.slug})


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Products
    template_name = 'product/product_add.html'
    fields = ['title', 'image', 'description', 'minimum_bid_price', 'end_time']
    #success_url = reverse_lazy('product/list.html')

    # To add author of the posted itmes
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Products
    fields = ['title', 'image', 'description', 'minimum_bid_price', 'end_time']
    template_name = 'product/product_update.html'

    # specific user can only update
    def test_func(self):
        obj = self.get_object()
        return obj.created_by == self.request.user


class UserProductListView(ListView):
    model = Products
    template_name = 'user/user_post.html'
    context_object_name = 'products'
    paginate_by = 5

    def get_queryset(self):
        queryset = Products.objects.filter(created_by=self.request.user)
        return queryset


class BidUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Bid
    fields = ['bid_price', ]
    template_name = 'bid/bid_edit.html'

    # specific user can only update
    def test_func(self):
        obj = self.get_object()
        return obj.created_by == self.request.user

pages/templates/bid/bid_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Eidt bid{% endblock title %}

{% block content %}
<h2>Put price</h2>
<div>
  <form method="post">
      {% csrf_token %}
      {{ form.as_table }}
      <button class="btn btn-success" type="submit">BID</button>
    </form>
</div>

{% endblock content %}

pages/templates/product/detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}{{ product.title }}{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.title }}</h1>
    {% if product.created_by == request.user %}
    <a href="{% url "pages:product_edit" product.pk product.slug %}" class="btn btn-warning">Edit</a>
    {% endif %}
    <p>add by:{{ product.created_by.username }}</p>
    <p class="price">Minimum Bid: ${{ product.minimum_bid_price }}</p>
    <p style="font-weight: bold;">Product Description:</p>{{ product.description|linebreaks }}
</div>
<br>
{% now "Y-m-d H:i" as today_date_time %}
{% if today_date_time < product.end_time|date:"Y-m-d H:i" %}
    {% if product.created_by != request.user %}
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <button class="btn btn-success" type="submit">BID</button>
      </form>
</div>
    {% endif %}
{% else %}
<div class="card-header" style="color: red; font-weight: bold">
    Bidding Time is Over !!
</div>
{% endif %}
    
<div>
    {% if today_date_time > product.end_time|date:"Y-m-d H:i" %}
        {% if product.bid_item.count %}
        <div class="card-header" style="color: green; font-weight: bold">Current Bid Winner: {{ bidder.created_by.username}}</div>
        {% endif %}   
    {% endif %}
    </div>
    {% if product.bid_item.count %}
    <table class="table mb-0">
        <thead>
            <tr>
              <th>Bidder</th>
              <th>Bid Price</th>
              <th>Action</th>
            </tr>
          </thead>
    <tbody>
        {% for bid in product.bid_item.all %}
        <tr>
            <td>
                {{ bid.created_by }}
            </td>
            <td>
                {{ bid.bid_price }}
            </td>
            <td>
                {% if today_date_time < product.end_time|date:"Y-m-d H:i" %}
                {% if product.created_by != request.user %}
                <a href="{% url "pages:bid_edit" bid.pk  %}" class="btn btn-warning">Edit</a>
                {% endif %}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    {% else %}
    <h1 class="text-danger"> No one Bid this item yet!!!!</h1>
    {% endif %}

{% else %}
    <p>You are not logged In.Please Log in</p>
    <p><a href="{% url 'account_login' %}">Log In</a>
{% endif %}
{% endblock %}

pages/templates/product/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

{% if user.is_authenticated %}
<h1>Ongoing Auction</h1>
<a class="btn btn-primary float-right" href="{% url "pages:product_add" %}" role="button">+Add Items</a>
<a class="btn btn-success float-right" href="{% url "pages:myposts" %}" role="button">My Posted Items</a>
<br>
<br>

<table class="table mb-0">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Title</th>
      <th>Minimum Bid</th>
      <th>EndTime</th>
      <th>Add By</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr>
      <td>
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static "img/no_image.png" %}{% endif %}"
            style="width:80px;">
        </a>
      </td>
      <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
      <td>
        ${{ product.minimum_bid_price }}
      </td>
      <td>
        {{ product.end_time }}
      </td>
      <td>{{ product.created_by.username }}</td>
      <td>
        {% now "Y-m-d H:i" as today_date_time %}
        {% if today_date_time < product.end_time|date:"Y-m-d H:i" %}
        <a  class="btn btn-primary" href="{{ product.get_absolute_url }}">Bid</a>
        {% else %}
        <p><div style="color: red; font-weight: bold">
          Bidding Time is Over !!
      </div>
        </p>
        {% endif %}
      </td>
    </tr>
    
    {% endfor %}
  </tbody>
</table>
<!-- Add pagination View -->
{% if is_paginated %}
<ul class="pagination">
  {% if page_obj.has_previous %}
  <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
  {% else %}
  <li class="page-item disabled"><span>&laquo;</span></li>
  {% endif %}
  {% for i in paginator.page_range %}
  {% if page_obj.number == i %}
  <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
  {% else %}
  <li><a href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
  <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
  {% else %}
  <li class="disabled"><span>&raquo;</span></li>
  {% endif %}
</ul>
{% endif %}

{% else %}
<h1>Your are not logged in. Please Log in</h1>

{% endif %}

{% endblock content %}

pages/templates/product/product_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Product{% endblock title %}

{% block content %}
<h2>Add New Item</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-success" type="submit">Sign Up</button>
</form>

{% endblock content %}

pages/templates/product/product_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Product{% endblock title %}

{% block content %}
<h2>Edit Item</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <button class="btn btn-info ml-2" type="submit">Update</button>
</form>

{% endblock content %}

pages/templates/user/user_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block content %}

{% if user.is_authenticated %}
<h1>My Posted Items</h1>
<a class="btn btn-primary float-right" href="{% url "pages:product_add" %}" role="button">+Add Items</a>
<br>
<br>
<table class="table mb-0">
    <thead>
        <tr>
            <th>Photo</th>
            <th>Title</th>
            <th>Minimum Bid</th>
            <th>EndTime</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td>
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{%else %}{% static "img/no_image.png" %}{% endif %}"
                        style="width:80px;">
                </a>
            </td>
            <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a></td>
            <td>
                ${{ product.minimum_bid_price }}
            </td>
            <td>
                {{ product.end_time }}
            </td>
            <td>{% if product.created_by == request.user %}
                <div>
                    | <a href="{% url "pages:product_edit" product.pk product.slug %}">Edit</a> |
                </div>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- Add pagination View -->
{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="page-item disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}

{% else %}
<h1>Your are not logged in. Please Log in</h1>

{% endif %}

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Auction{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">

  <!-- list_css -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
  <header>
    <!-- Fixed navbar -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4
     mb-3 bg-white border-bottom shadow-sm">
      <a href="{% url 'pages:product_list' %}" class="navbar-brand my-0 mr-md-auto
      font-weight-normal">Auction</a>
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        <a class="p-2 text-dark" >{{ user.username }}</a>
          <a class="btn btn-outline-primary" href="{% url 'account_logout' %}">Log Out</a>
        {% else %}
          <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
          <a class="btn btn-outline-primary" href="{% url 'account_signup' %}">Sign Up</a>
  {% endif %}
</nav>
    </div>
  </header>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  <!--JS, Popper.js, and jQuery -->
 <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" integrity="sha384-1CmrxMRARb6aLqgBO7yyAxTOQE2AKb9GfXnEo760AUcUmFx3ibVJJAzGytlQcNXd" crossorigin="anonymous"></script>
  
  <!-- list js -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>